- name: create user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory
  anisble.builtin.file:
    path: /app
    state: absent

- name: create app directory
  anisble.builtin.file:
    path: /app
    state: directory

- name: download app content from url
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: extract app content
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes